# -*- coding: utf-8 -*-
"""Dashboard_Streamlit10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDYR-8p414GtpUhmuIvINEoQATlHkEaS
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import time
from textwrap import dedent

st.set_page_config(
    page_title="Solar GHI Forecasting Dashboard",
    layout="wide"
)

st.markdown(
    "<h1 style='text-align: center;'>☀️ Solar GHI Forecasting Dashboard</h1>",
    unsafe_allow_html=True
)

DATA_PATH = "Bias Correction_with_Day_Ahead_2hrahead_Forecast_3.csv"
DAYAHEAD_PATH = "7_day_average_forecast.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)
    dayahead_df = pd.read_csv(DAYAHEAD_PATH)

    df["valid_time_ist"] = (
        pd.to_datetime(df["valid_time_ist"])
          .dt.tz_localize(None)
    )
    df["valid_time_ist"] = pd.to_datetime(df["valid_time_ist"])
    dayahead_df["valid_time_ist"] = (
        pd.to_datetime(dayahead_df["valid_time_ist"])
          .dt.tz_localize(None)
    )

    dayahead_df = dayahead_df[
        [
            "valid_time_ist",
            "Seven_Day_Average_Forecast"
        ]
    ]
    
    df = df.merge(
        dayahead_df,
        on="valid_time_ist",
        how="left"
    )

    df = df.rename(columns={
        "avg_ghi": "GFS_GHI",
        "ALLSKY_SFC_SW_DWN": "Actual_GHI",
        "Day_Ahead_Forecast": "Daily_Forecast_GHI",
        "2hr_ahead_forecast": "Two_Hour_Ahead_Forecast",
        "Seven_Day_Average_Forecast":"Day_Ahead_Forecast_GHI"
    })

    df = df.sort_values("valid_time_ist").reset_index(drop=True)
    return df

df = load_data()

def show_section_heading(
    title,
    start_date=None,
    end_date=None,
    icon="",
    heading_size="1.5rem",
    top_margin="18px",
    bottom_margin="12px"
):
    date_html = ""

    if start_date is not None:

        if end_date is not None and end_date != "":
            date_text = f"{start_date} to {end_date}"
        else:
            date_text = f"{start_date}"

        date_html = f"""
        <div style="
            font-size:1.5rem;
            font-weight:600;
            color:inherit;
            margin-top:6px;
        ">
            {date_text}
        </div>
        """

    st.markdown(
        f"""
        <div style="
            margin-top:{top_margin};
            margin-bottom:{bottom_margin};
        ">
            <div style="
                font-size:{heading_size};
                font-weight:700;
                line-height:1.2;
            ">
                {icon} {title}
            </div>
            {date_html}
        </div>
        """,
        unsafe_allow_html=True
    )

# =====================================================
# CACHED MONTH-WISE MAE — 2-HOUR AHEAD FORECAST
# One bar per calendar month across all years
# =====================================================

@st.cache_data
def calculate_monthly_2hr_mae(input_df):

    monthly_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    monthly_df["hour"] = (
        monthly_df["valid_time_ist"].dt.hour
        + monthly_df["valid_time_ist"].dt.minute / 60
    )

    monthly_df = monthly_df[
        (monthly_df["hour"] >= 6.5)
        & (monthly_df["hour"] <= 17.5)
        & (monthly_df["Actual_GHI"] > 50)
    ].copy()

    if monthly_df.empty:
        return pd.DataFrame(), None, None

    monthly_df["Absolute_Error"] = (
        monthly_df["Actual_GHI"]
        - monthly_df["Two_Hour_Ahead_Forecast"]
    ).abs()

    monthly_df["Month_Number"] = (
        monthly_df["valid_time_ist"].dt.month
    )

    monthly_result = (
        monthly_df
        .groupby("Month_Number", as_index=False)
        .agg(Monthly_MAE=("Absolute_Error", "mean"))
        .sort_values("Month_Number")
        .reset_index(drop=True)
    )

    month_names = {
        1: "Jan",
        2: "Feb",
        3: "Mar",
        4: "Apr",
        5: "May",
        6: "Jun",
        7: "Jul",
        8: "Aug",
        9: "Sep",
        10: "Oct",
        11: "Nov",
        12: "Dec"
    }

    monthly_result["Month"] = (
        monthly_result["Month_Number"].map(month_names)
    )

    start_date = monthly_df["valid_time_ist"].dt.date.min()
    end_date = monthly_df["valid_time_ist"].dt.date.max()

    return monthly_result, start_date, end_date

st.subheader("🏭 Plant & Forecast Configuration")

available_dates = sorted(df["valid_time_ist"].dt.date.unique())

c1, c2, c3, c4 = st.columns([1, 1.5, 1, 1])

with c1:
    state = st.selectbox(
        "State",
        ["Karnataka"]
    )

with c2:
    plant = st.selectbox(
        "Plant Name",
        ["Pavagada Solar Plant"]
    )

with c3:
    selected_date = st.date_input(
        "Date",
        value=available_dates[-1],
        min_value=available_dates[0],
        max_value=available_dates[-1]
    )

with c4:
    time_options = pd.date_range("06:30", "17:30", freq="1h").time

    selected_time = st.selectbox(
        "Time",
        options=time_options,
        format_func=lambda t: t.strftime("%H:%M")
    )


day_df = df[df["valid_time_ist"].dt.date == selected_date].copy()

# =====================================================
# NEXT DAY (DAY-AHEAD) FORECAST
# =====================================================

next_date = selected_date + pd.Timedelta(days=1)

next_day_df = df[
    df["valid_time_ist"].dt.date == next_date
].copy()

next_day_df["hour"] = (
    next_day_df["valid_time_ist"].dt.hour +
    next_day_df["valid_time_ist"].dt.minute / 60
)

next_day_df = next_day_df[
    (next_day_df["hour"] >= 6.5) &
    (next_day_df["hour"] <= 17.5)
]

has_day_ahead = (
    not next_day_df.empty
    and
    next_day_df["Day_Ahead_Forecast_GHI"].notna().any()
)

day_df["hour"] = (
    day_df["valid_time_ist"].dt.hour +
    day_df["valid_time_ist"].dt.minute / 60
)

day_df = day_df[
    (day_df["hour"] >= 6.5) &
    (day_df["hour"] <= 17.5)
].copy()

selected_datetime = pd.to_datetime(
    str(selected_date) + " " + selected_time.strftime("%H:%M")
)

# =====================================================
# ACTUAL GHI AVAILABLE THROUGH THE PREVIOUS HOUR
# =====================================================

previous_hour_time = selected_datetime - pd.Timedelta(hours=1)

actual_until_previous_hour_df = day_df[
    day_df["valid_time_ist"] <= previous_hour_time
].dropna(
    subset=["Actual_GHI"]
).copy()

two_hour_end_time = selected_datetime + pd.Timedelta(hours=2)

target_row = day_df[
    day_df["valid_time_ist"] == two_hour_end_time
]

has_two_hour_forecast = (
    not target_row.empty and
    pd.notna(target_row["Two_Hour_Ahead_Forecast"].iloc[0])
)

if has_two_hour_forecast:
    two_hour_df = day_df[
        day_df["valid_time_ist"] <= two_hour_end_time
    ].copy()

    two_hour_df = two_hour_df.dropna(
        subset=["Two_Hour_Ahead_Forecast"]
    )
else:
    two_hour_df = pd.DataFrame()


if day_df.empty:
    st.stop()

else:

    left_col, right_col = st.columns(2)

    ymax = max(
        day_df["Actual_GHI"].max(),
        day_df["GFS_GHI"].max(),
        day_df["Daily_Forecast_GHI"].max()
    )

    ymax = (int(ymax / 100) + 1) * 100

    tick_times = day_df["valid_time_ist"].dt.strftime("%H:%M").tolist()

    # ============================
    # Dashboard Colors
    # ============================
    GFS_COLOR = "#76B7F2"             # Light blue
    DAILY_FORECAST_COLOR = "#F28E2B"  # Orange
    DAILY_FORECAST_FILL = "rgba(242,142,43,0.25)"
    TWO_HOUR_COLOR = "#2CA02C"        # Green
    ACTUAL_COLOR = "#636EFA"          # Blue

    # =====================================================
    # FIRST ROW: DAILY FORECAST GHI ONLY
    # =====================================================

    fig1 = go.Figure()

    fig1.add_trace(go.Scatter(
        x=day_df["valid_time_ist"],
        y=day_df["Daily_Forecast_GHI"],
        mode="lines+markers",
        name="Intraday Forecast GHI",
        line=dict(color=DAILY_FORECAST_COLOR, width=2),
        marker=dict(color=DAILY_FORECAST_COLOR),
         fill="tozeroy",
        fillcolor=DAILY_FORECAST_FILL
    ))

    if has_day_ahead:
        
        fig1.add_trace(go.Scatter(

            x=next_day_df["valid_time_ist"],
    
            y=next_day_df["Day_Ahead_Forecast_GHI"],
    
            mode="lines+markers",
    
            name="Day-Ahead Forecast",
    
            line=dict(
                color="#8E44AD",
                width=2
            ),
    
            marker=dict(
                color="#8E44AD"
            )
    
        ))

    if has_two_hour_forecast:

        fig1.add_trace(go.Scatter(
            x=two_hour_df["valid_time_ist"],
            y=two_hour_df["Two_Hour_Ahead_Forecast"],
            mode="lines+markers",
            name="2-Hour Ahead Forecast",
            line=dict(color=TWO_HOUR_COLOR),
            marker=dict(color=TWO_HOUR_COLOR)
        ))

    else:
        pass

    fig1.update_layout(
        title=dict(
            text=f"☀️ Forecasted GHI for {selected_date}",
            font=dict(size=30)
        ),
        xaxis_title="Time",
        yaxis_title="GHI",
        height=450,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )


    fig1.update_xaxes(
        tickmode="array",
        tickvals=day_df["valid_time_ist"],
        ticktext=tick_times
    )

    fig1.update_yaxes(range=[0, ymax])

    row1_col, row1_space = st.columns([4.5, 0.8])

    with row1_col:
        
        st.plotly_chart(
            fig1,
            use_container_width=True,
            key="daily_forecast_main"
        )

        if not has_day_ahead:
            
            st.info(
                "Day-ahead forecast is not available for the selected day."
            )

    with row1_space:

        with st.container(border=True):

            st.markdown("### 📥 Export Forecast Data")

            download_cols = [
                "valid_time_ist",
                "Actual_GHI",
                "GFS_GHI",
                "Daily_Forecast_GHI",
                "Two_Hour_Ahead_Forecast"
            ]

            rename_download_cols = {
                "valid_time_ist": "Time",
                "Actual_GHI": "Actual GHI",
                "GFS_GHI": "GFS GHI",
                "Daily_Forecast_GHI": "Intraday Forecast GHI",
                "Two_Hour_Ahead_Forecast": "2-Hour Ahead Forecast GHI"
            }

            # =====================================================
            # DOWNLOAD 1: START OF DATA TO SELECTED DATE
            # =====================================================

            cumulative_download_df = df[
                df["valid_time_ist"].dt.date <= selected_date
            ].copy()

            cumulative_download_df["hour"] = (
                cumulative_download_df["valid_time_ist"].dt.hour
                + cumulative_download_df["valid_time_ist"].dt.minute / 60
            )

            cumulative_download_df = cumulative_download_df[
                (cumulative_download_df["hour"] >= 6.5)
                & (cumulative_download_df["hour"] <= 17.5)
            ].copy()

            cumulative_download_df = cumulative_download_df[
                download_cols
            ].rename(columns=rename_download_cols)

            cumulative_csv = cumulative_download_df.to_csv(
                index=False
            ).encode("utf-8")


            st.download_button(
                label="⬇️ Download data through selected date",
                data=cumulative_csv,
                file_name=f"forecast_data_through_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_cumulative_forecast"
            )


            # =====================================================
            # DOWNLOAD 2: SELECTED DATE ONLY
            # =====================================================

            day_download_df = day_df[
                download_cols
            ].copy().rename(columns=rename_download_cols)

            day_csv = day_download_df.to_csv(
                index=False
            ).encode("utf-8")

            st.download_button(
                label="⬇️ Download selected day data",
                data=day_csv,
                file_name=f"forecast_data_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_selected_day_forecast"
            )

    # =====================================================
    # SECOND ROW: TWO PLOTS
    # LEFT: GFS VS DAILY FORECAST
    # RIGHT: DAILY FORECAST GHI ONLY
    # =====================================================

    st.markdown(
        """
        <h2 style="
            margin-top:20px;
            margin-bottom:10px;
            font-size:1.65rem;
            font-weight:700;
        ">
            📈 Forecast Performance Comparison
        </h2>
        """,
        unsafe_allow_html=True
    )

    left_col, right_col = st.columns(2)

    with left_col:

        with st.container(border=True):

            fig2 = go.Figure()

            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["GFS_GHI"],
                mode="lines+markers",
                name="GFS GHI",
                line=dict(color=GFS_COLOR),
                marker=dict(color=GFS_COLOR)
            ))

            if not actual_until_previous_hour_df.empty:
                
                fig2.add_trace(go.Scatter(
                    x=actual_until_previous_hour_df["valid_time_ist"],
                    y=actual_until_previous_hour_df["Actual_GHI"],
                    mode="lines+markers",
                    name="Actual GHI (Available)",
                    line=dict(
                        color=ACTUAL_COLOR,
                        dash="dot",
                        width=2
                    ),
                    marker=dict(
                        color=ACTUAL_COLOR
                    )
                ))

            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["Daily_Forecast_GHI"],
                mode="lines+markers",
                name="Intraday Forecast GHI",
                line=dict(color=DAILY_FORECAST_COLOR),
                marker=dict(color=DAILY_FORECAST_COLOR)

            ))

            fig2.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )

            fig2.update_xaxes(
                tickmode="array",
                tickvals=day_df["valid_time_ist"],
                ticktext=tick_times
            )

            fig2.update_yaxes(range=[0, ymax])

            st.plotly_chart(
                fig2,
                use_container_width=True,
                key="gfs_vs_daily_forecast"
            )


    with right_col:
        with st.container(border=True):

            fig3 = go.Figure()

            if has_two_hour_forecast:
                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                actual_2hr_plot_df = day_df[
                    (day_df["valid_time_ist"] >= two_hour_df["valid_time_ist"].min()) &
                    (day_df["valid_time_ist"] <= previous_hour_time)
                ].dropna(
                    subset=["Actual_GHI"]
                ).copy()
            
                if not actual_2hr_plot_df.empty:
            
                    fig3.add_trace(go.Scatter(
                        x=actual_2hr_plot_df["valid_time_ist"],
                        y=actual_2hr_plot_df["Actual_GHI"],
                        mode="lines+markers",
                        name="Actual GHI (Available)",
                        line=dict(
                            color=ACTUAL_COLOR,
                            dash="dot",
                            width=2
                        ),
                        marker=dict(color=ACTUAL_COLOR)
                    ))

                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["Daily_Forecast_GHI"],
                    mode="lines+markers",
                    name="Intraday Forecast GHI",
                    line=dict(color=DAILY_FORECAST_COLOR),
                    marker=dict(color=DAILY_FORECAST_COLOR)
                ))

                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["Two_Hour_Ahead_Forecast"],
                    mode="lines+markers",
                    name="2-Hour Ahead Forecast",
                    line=dict(color=TWO_HOUR_COLOR),
                    marker=dict(color=TWO_HOUR_COLOR)
                ))

                fig3_tick_vals = two_hour_df["valid_time_ist"]
                fig3_tick_times = (
                    two_hour_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )

            else:
                selected_target_time = two_hour_end_time.strftime("%H:%M")

                st.warning(
                    f"No 2-hour ahead forecast available on {selected_date} "
                    f"for selected time {selected_time.strftime('%H:%M')} "
                    f"(target time: {selected_target_time})"
                )

                fig3_tick_vals = day_df["valid_time_ist"]
                fig3_tick_times = (
                    day_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )

            fig3.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )

            fig3.update_xaxes(
                tickmode="array",
                tickvals=fig3_tick_vals,
                ticktext=fig3_tick_times
            )

            fig3.update_yaxes(range=[0, ymax])

            st.plotly_chart(
                fig3,
                use_container_width=True,
                key="two_hour_gfs_comparison"
            )

    # =====================================================
    # PREVIOUS DAY COMPARISON PLOTS
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    previous_df = df[
        df["valid_time_ist"].dt.date == previous_day
    ].copy()

    previous_df["hour"] = (
        previous_df["valid_time_ist"].dt.hour
        + previous_df["valid_time_ist"].dt.minute / 60
    )

    previous_df = previous_df[
        (previous_df["hour"] >= 6.5)
        & (previous_df["hour"] <= 17.5)
    ].copy()

    if previous_df.empty:
        st.warning(
            f"No previous-day data available for {previous_day}."
        )

    else:

        show_section_heading(
            title="Previous Day Performance Comparison of Forecasted GHI",
            start_date=previous_day,
            icon="📈",
            heading_size="2.0rem"
        )

        # Common y-axis maximum
        prev_ymax = max(
            previous_df["Actual_GHI"].max(),
            previous_df["GFS_GHI"].max(),
            previous_df["Daily_Forecast_GHI"].max(),
            previous_df["Two_Hour_Ahead_Forecast"].max(skipna=True)
        )

        prev_ymax = (int(prev_ymax / 100) + 1) * 100

        prev_tick_times = (
            previous_df["valid_time_ist"]
            .dt.strftime("%H:%M")
            .tolist()
        )

        prev_left, prev_right = st.columns(2)

        # =====================================================
        # PREVIOUS DAY LEFT PLOT
        # Actual + GFS + Daily Forecast
        # =====================================================

        with prev_left:
            with st.container(border=True):

                fig_prev1 = go.Figure()

                # Actual GHI — green dotted
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Actual_GHI"],
                    mode="lines+markers",
                    name="Actual GHI",
                    line=dict(color=ACTUAL_COLOR, dash="dot"),
                    marker=dict(color=ACTUAL_COLOR)
                ))

                # GFS GHI — blue
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                # Daily Forecast — orange
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Daily_Forecast_GHI"],
                    mode="lines+markers",
                    name="Intraday Forecast GHI",
                    line=dict(color=DAILY_FORECAST_COLOR),
                    marker=dict(color=DAILY_FORECAST_COLOR)
                ))

                fig_prev1.update_layout(
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev1.update_xaxes(
                    tickmode="array",
                    tickvals=previous_df["valid_time_ist"],
                    ticktext=prev_tick_times
                )

                fig_prev1.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev1,
                    use_container_width=True,
                    key="previous_day_actual_gfs_forecast"
                )

        # =====================================================
        # PREVIOUS DAY RIGHT PLOT
        # Actual + GFS + 2-Hour Ahead
        # =====================================================

        with prev_right:
            with st.container(border=True):

                fig_prev2 = go.Figure()

                # Since the previous day is complete, use all rows
                # where 2-hour-ahead forecast exists.
                previous_two_hour_df = previous_df.dropna(
                    subset=["Two_Hour_Ahead_Forecast"]
                ).copy()

                if not previous_two_hour_df.empty:

                    # Actual GHI — green dotted
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["Actual_GHI"],
                        mode="lines+markers",
                        name="Actual GHI",
                        line=dict(color=ACTUAL_COLOR, dash="dot"),
                        marker=dict(color=ACTUAL_COLOR)
                    ))

                    # GFS GHI — blue
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["GFS_GHI"],
                        mode="lines+markers",
                        name="GFS GHI",
                        line=dict(color=GFS_COLOR),
                        marker=dict(color=GFS_COLOR)
                    ))

                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["Daily_Forecast_GHI"],
                        mode="lines+markers",
                        name="Intraday Forecast GHI",
                        line=dict(color=DAILY_FORECAST_COLOR),
                        marker=dict(color=DAILY_FORECAST_COLOR)
                    ))

                    # 2-Hour Ahead Forecast — red
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df[
                            "Two_Hour_Ahead_Forecast"
                        ],
                        mode="lines+markers",
                        name="2-Hour Ahead Forecast",
                        line=dict(color=TWO_HOUR_COLOR),
                        marker=dict(color=TWO_HOUR_COLOR)

                    ))

                    prev2_tick_vals = (
                        previous_two_hour_df["valid_time_ist"]
                    )

                    prev2_tick_text = (
                        previous_two_hour_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                else:
                    st.warning(
                        f"No previous-day 2-hour ahead forecast "
                        f"data available for {previous_day}."
                    )

                    prev2_tick_vals = previous_df["valid_time_ist"]

                    prev2_tick_text = (
                        previous_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                fig_prev2.update_layout(
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev2.update_xaxes(
                    tickmode="array",
                    tickvals=prev2_tick_vals,
                    ticktext=prev2_tick_text
                )

                fig_prev2.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev2,
                    use_container_width=True,
                    key="previous_day_two_hour_actual_gfs"
                )


    # =====================================================
    # CUMULATIVE ERROR METRICS: START DATE TO PREVIOUS DAY
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    eval_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    eval_df = eval_df.dropna(
        subset=["Actual_GHI", "GFS_GHI", "Daily_Forecast_GHI"]
    )

    eval_df["hour"] = (
        eval_df["valid_time_ist"].dt.hour +
        eval_df["valid_time_ist"].dt.minute / 60
    )

    eval_df = eval_df[
        (eval_df["hour"] >= 6.5) &
        (eval_df["hour"] <= 17.5) &
        (eval_df["Actual_GHI"] > 50)
    ].copy()

    if not eval_df.empty:

        start_date = eval_df["valid_time_ist"].dt.date.min()
        end_date = eval_df["valid_time_ist"].dt.date.max()

        actual = eval_df["Actual_GHI"]
        before = eval_df["GFS_GHI"]
        after = eval_df["Daily_Forecast_GHI"]

        mae_before = (actual - before).abs().mean()
        mae_after = (actual - after).abs().mean()

        rmse_before = np.sqrt(((actual - before) ** 2).mean())
        rmse_after = np.sqrt(((actual - after) ** 2).mean())

        mape_before = ((actual - before).abs() / actual).mean() * 100
        mape_after = ((actual - after).abs() / actual).mean() * 100

        show_section_heading(
            title="Cumulative Performance of Intraday Forecast",
            start_date=start_date,
            end_date=end_date,
            icon="📊",
            heading_size="2.0rem"
        )


        metric_col1, metric_col2, metric_col3 = st.columns(3)

        # ---------------- MAPE ----------------
        with metric_col1:
            fig_mape = go.Figure()

            fig_mape.add_trace(go.Bar(
                x=["Raw GFS", "Intraday Forecast"],
                y=[mape_before, mape_after],
                text=[round(mape_before, 2), round(mape_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_mape.update_layout(
                title="MAPE",
                xaxis_title="Forecast Stage",
                yaxis_title="MAPE (%)",
                height=350
            )

            st.plotly_chart(
                fig_mape,
                use_container_width=True,
                key="mape_cumulative_chart"
            )

        # ---------------- MAE ----------------
        with metric_col2:
            fig_mae = go.Figure()

            fig_mae.add_trace(go.Bar(
                x=["Raw GFS", "Intraday Forecast"],
                y=[mae_before, mae_after],
                text=[round(mae_before, 2), round(mae_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_mae.update_layout(
                title="MAE",
                xaxis_title="Forecast Stage",
                yaxis_title="MAE",
                height=350
            )

            st.plotly_chart(
                fig_mae,
                use_container_width=True,
                key="mae_cumulative_chart"
            )

        # ---------------- RMSE ----------------
        with metric_col3:
            fig_rmse = go.Figure()

            fig_rmse.add_trace(go.Bar(
                x=["Raw GFS", "Intraday Forecast"],
                y=[rmse_before, rmse_after],
                text=[round(rmse_before, 2), round(rmse_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_rmse.update_layout(
                title="RMSE",
                xaxis_title="Forecast Stage",
                yaxis_title="RMSE",
                height=350
            )

            st.plotly_chart(
                fig_rmse,
                use_container_width=True,
                key="rmse_cumulative_chart"
            )

    else:
        st.warning(
            "Not enough valid previous-day data to calculate cumulative forecast performance."
        )

    # =====================================================
    # CUMULATIVE 2-HOUR-AHEAD FORECAST PERFORMANCE
    # Start of data through previous day
    # =====================================================

    cumulative_2hr_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    cumulative_2hr_df["hour"] = (
        cumulative_2hr_df["valid_time_ist"].dt.hour
        + cumulative_2hr_df["valid_time_ist"].dt.minute / 60
    )

    # Use only rows where all required values are available
    cumulative_2hr_df = cumulative_2hr_df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    cumulative_2hr_df = cumulative_2hr_df[
        (cumulative_2hr_df["hour"] >= 6.5)
        & (cumulative_2hr_df["hour"] <= 17.5)
        & (cumulative_2hr_df["Actual_GHI"] > 50)
    ].copy()

    if not cumulative_2hr_df.empty:

        cumulative_2hr_start = (
            cumulative_2hr_df["valid_time_ist"]
            .dt.date
            .min()
        )

        cumulative_2hr_end = (
            cumulative_2hr_df["valid_time_ist"]
            .dt.date
            .max()
        )

        show_section_heading(
            title="Cumulative Performance of 2-Hour Ahead Forecast",
            start_date=cumulative_2hr_start,
            end_date=cumulative_2hr_end,
            icon="📊",
            heading_size="2.0rem"
        )

        actual_cum_2hr = cumulative_2hr_df["Actual_GHI"]
        gfs_cum_2hr = cumulative_2hr_df["GFS_GHI"]
        daily_cum_2hr = cumulative_2hr_df[
            "Daily_Forecast_GHI"
        ]
        forecast_cum_2hr = cumulative_2hr_df[
            "Two_Hour_Ahead_Forecast"
        ]

        # =====================================================
        # MAPE
        # =====================================================

        cumulative_mape_gfs = (
            (
                (actual_cum_2hr - gfs_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        cumulative_mape_daily = (
            (
                (actual_cum_2hr - daily_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        cumulative_mape_2hr = (
            (
                (actual_cum_2hr - forecast_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        # =====================================================
        # MAE
        # =====================================================

        cumulative_mae_gfs = (
            actual_cum_2hr - gfs_cum_2hr
        ).abs().mean()

        cumulative_mae_daily = (
            actual_cum_2hr - daily_cum_2hr
        ).abs().mean()

        cumulative_mae_2hr = (
            actual_cum_2hr - forecast_cum_2hr
        ).abs().mean()

        # =====================================================
        # RMSE
        # =====================================================

        cumulative_rmse_gfs = np.sqrt(
            ((actual_cum_2hr - gfs_cum_2hr) ** 2).mean()
        )

        cumulative_rmse_daily = np.sqrt(
            ((actual_cum_2hr - daily_cum_2hr) ** 2).mean()
        )

        cumulative_rmse_2hr = np.sqrt(
            ((actual_cum_2hr - forecast_cum_2hr) ** 2).mean()
        )

        comparison_labels = [
            "Raw GFS",
            "Intraday Forecast",
            "2 Hour Ahead"
        ]

        comparison_colors = [
            GFS_COLOR,
            DAILY_FORECAST_COLOR,
            TWO_HOUR_COLOR
        ]

        twohr_metric_col1, twohr_metric_col2, twohr_metric_col3 = (
            st.columns(3)
        )

        # =====================================================
        # CUMULATIVE 2-HOUR MAPE
        # =====================================================

        with twohr_metric_col1:
            with st.container(border=True):

                fig_2hr_mape = go.Figure()

                fig_2hr_mape.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_mape_gfs,
                        cumulative_mape_daily,
                        cumulative_mape_2hr
                    ],
                    text=[
                        f"{cumulative_mape_gfs:.2f}",
                        f"{cumulative_mape_daily:.2f}",
                        f"{cumulative_mape_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_mape.update_layout(
                    title="MAPE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="MAPE (%)",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_mape,
                    use_container_width=True,
                    key="cumulative_2hr_mape_chart"
                )

        # =====================================================
        # CUMULATIVE 2-HOUR MAE
        # =====================================================

        with twohr_metric_col2:
            with st.container(border=True):

                fig_2hr_mae = go.Figure()

                fig_2hr_mae.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_mae_gfs,
                        cumulative_mae_daily,
                        cumulative_mae_2hr
                    ],
                    text=[
                        f"{cumulative_mae_gfs:.2f}",
                        f"{cumulative_mae_daily:.2f}",
                        f"{cumulative_mae_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_mae.update_layout(
                    title="MAE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="MAE",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_mae,
                    use_container_width=True,
                    key="cumulative_2hr_mae_chart"
                )

        # =====================================================
        # CUMULATIVE 2-HOUR RMSE
        # =====================================================

        with twohr_metric_col3:
            with st.container(border=True):

                fig_2hr_rmse = go.Figure()

                fig_2hr_rmse.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_rmse_gfs,
                        cumulative_rmse_daily,
                        cumulative_rmse_2hr
                    ],
                    text=[
                        f"{cumulative_rmse_gfs:.2f}",
                        f"{cumulative_rmse_daily:.2f}",
                        f"{cumulative_rmse_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_rmse.update_layout(
                    title="RMSE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="RMSE",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_rmse,
                    use_container_width=True,
                    key="cumulative_2hr_rmse_chart"
                )

    else:
        show_section_heading(
            title="Cumulative Performance of 2-Hour Ahead Forecast",
            start_date="Beginning of dataset",
            end_date=previous_day,
            icon="📊",
            heading_size="2.0rem"
        )

        st.warning(
            "No valid 2-hour-ahead forecast data is available "
            "from the beginning of the dataset through the previous day."
        )

    # =====================================================
    # OVERALL FULL-DATA PERFORMANCE METRICS
    # =====================================================

    overall_df = df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI"
        ]
    ).copy()

    overall_df["hour"] = (
        overall_df["valid_time_ist"].dt.hour
        + overall_df["valid_time_ist"].dt.minute / 60
    )

    overall_df = overall_df[
        (overall_df["hour"] >= 6.5)
        & (overall_df["hour"] <= 17.5)
        & (overall_df["Actual_GHI"] > 50)
    ].copy()

    # =====================================================
    # METRIC CARD FUNCTION
    # =====================================================

    def show_metric_card(title, metric_rows):
        """
        metric_rows:
        [
            (label, displayed_value, value_color, font_size),
            ...
        ]
        """

        with st.container(border=True):

            st.markdown(
                f"""
                <h3 style="
                    color:#FF3B30;
                    font-size:1.45rem;
                    margin-top:0;
                    margin-bottom:14px;
                ">
                    {title}
                </h3>
                """,
                unsafe_allow_html=True
            )

            for row_number, row in enumerate(metric_rows):

                label = row[0]
                displayed_value = row[1]
                value_color = row[2]
                font_size = row[3]

                metric_html = (
                    f'<div style="'
                    f'padding-top:12px;'
                    f'padding-bottom:12px;">'

                    f'<div style="'
                    f'font-size:0.88rem;'
                    f'font-weight:600;'
                    f'margin-bottom:5px;'
                    f'color:inherit;">'
                    f'{label}'
                    f'</div>'

                    f'<div style="'
                    f'color:{value_color};'
                    f'font-size:{font_size};'
                    f'font-weight:750;'
                    f'line-height:1.15;">'
                    f'{displayed_value}'
                    f'</div>'

                    f'</div>'
                )

                st.markdown(
                    metric_html,
                    unsafe_allow_html=True
                )

    if not overall_df.empty:

        # =====================================================
        # DAILY FORECAST METRICS
        # =====================================================

        daily_start_date = (
            overall_df["valid_time_ist"].dt.date.min()
        )

        daily_end_date = (
            overall_df["valid_time_ist"].dt.date.max()
        )

        actual_all = overall_df["Actual_GHI"]
        gfs_all = overall_df["GFS_GHI"]
        daily_all = overall_df["Daily_Forecast_GHI"]

        overall_mape_before = (
            ((actual_all - gfs_all).abs() / actual_all).mean()
            * 100
        )

        overall_mape_after = (
            ((actual_all - daily_all).abs() / actual_all).mean()
            * 100
        )

        overall_mae_before = (
            (actual_all - gfs_all).abs().mean()
        )

        overall_mae_after = (
            (actual_all - daily_all).abs().mean()
        )

        overall_rmse_before = np.sqrt(
            ((actual_all - gfs_all) ** 2).mean()
        )

        overall_rmse_after = np.sqrt(
            ((actual_all - daily_all) ** 2).mean()
        )

        st.markdown("## 📑 Overall Forecast Performance")

        left_summary, right_summary = st.columns(2)

        # =====================================================
        # LEFT SIDE: DAILY FORECAST
        # =====================================================

        with left_summary:

            with st.container(border=True):

                show_section_heading(
                    title="Intraday Forecast",
                    start_date=daily_start_date,
                    end_date=daily_end_date,
                    icon="📈",
                    heading_size="1.5rem",
                    top_margin="2px",
                    bottom_margin="8px"
                )

                st.markdown(
                    """
                    <div style="
                        font-size:0.92rem;
                        color:inherit;
                        margin-bottom:2px;
                    ">
                        Comparison of Actual GHI, GFS and Intraday Forecast GHI
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            k1, k2, k3 = st.columns(3)

            # ---------------- MAPE ----------------
            with k1:
                show_metric_card(
                    "🎯 MAPE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_mape_before:.2f}%",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Intraday Forecast",
                            f"{overall_mape_after:.2f}%",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

            # ---------------- MAE ----------------
            with k2:
                show_metric_card(
                    "📊 MAE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_mae_before:.2f}",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Intraday Forecast",
                            f"{overall_mae_after:.2f}",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

            # ---------------- RMSE ----------------
            with k3:
                show_metric_card(
                    "〽️ RMSE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_rmse_before:.2f}",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Intraday Forecast",
                            f"{overall_rmse_after:.2f}",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

        # =====================================================
        # RIGHT SIDE: 2-HOUR-AHEAD FORECAST
        # =====================================================

        with right_summary:

            two_hour_metrics_df = overall_df.dropna(
                subset=["Two_Hour_Ahead_Forecast"]
            ).copy()

            if not two_hour_metrics_df.empty:

                twohr_start_date = (
                    two_hour_metrics_df[
                        "valid_time_ist"
                    ].dt.date.min()
                )

                twohr_end_date = (
                    two_hour_metrics_df[
                        "valid_time_ist"
                    ].dt.date.max()
                )

                actual_2hr = (
                    two_hour_metrics_df["Actual_GHI"]
                )

                gfs_2hr = (
                    two_hour_metrics_df["GFS_GHI"]
                )

                daily_2hr = (
                    two_hour_metrics_df["Daily_Forecast_GHI"]
                )

                forecast_2hr = (
                    two_hour_metrics_df[
                        "Two_Hour_Ahead_Forecast"
                    ]
                )

                # =====================================================
                # MAPE
                # =====================================================

                mape_gfs = (
                    (
                        (actual_2hr - gfs_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                mape_daily = (
                    (
                        (actual_2hr - daily_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                mape_2hr = (
                    (
                        (actual_2hr - forecast_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                # =====================================================
                # MAE
                # =====================================================

                mae_gfs = (
                    (actual_2hr - gfs_2hr).abs().mean()
                )

                mae_daily = (
                    (actual_2hr - daily_2hr).abs().mean()
                )

                mae_2hr = (
                    (actual_2hr - forecast_2hr).abs().mean()
                )

                # =====================================================
                # RMSE
                # =====================================================

                rmse_gfs = np.sqrt(
                    ((actual_2hr - gfs_2hr) ** 2).mean()
                )

                rmse_daily = np.sqrt(
                    ((actual_2hr - daily_2hr) ** 2).mean()
                )

                rmse_2hr = np.sqrt(
                    ((actual_2hr - forecast_2hr) ** 2).mean()
                )

                with st.container(border=True):

                    show_section_heading(
                        title="2-Hour Ahead Forecast",
                        start_date=twohr_start_date,
                        end_date=twohr_end_date,
                        icon="🕒",
                        heading_size="1.5rem",
                        top_margin="2px",
                        bottom_margin="8px"
                    )

                    st.markdown(
                        """
                        <div style="
                            font-size:0.92rem;
                            color:inherit;
                            margin-bottom:2px;
                        ">
                            Calculated only for rows where
                            2-Hour Ahead Forecast is available
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                h1, h2, h3 = st.columns(3)

                # ---------------- MAPE ----------------
                with h1:
                    show_metric_card(
                        "🎯 MAPE",
                        [
                            (
                                "Actual vs GFS",
                                f"{mape_gfs:.2f}%",
                                GFS_COLOR,
                                "1.40rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{mape_2hr:.2f}%",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

                # ---------------- MAE ----------------
                with h2:
                    show_metric_card(
                        "📊 MAE",
                        [
                            (
                                "Actual vs GFS",
                                f"{mae_gfs:.2f}",
                                GFS_COLOR,
                                "1.40rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{mae_2hr:.2f}",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

                # ---------------- RMSE ----------------
                with h3:
                    show_metric_card(
                        "〽️ RMSE",
                        [
                            (
                                "Actual vs GFS",
                                f"{rmse_gfs:.2f}",
                                GFS_COLOR,
                                "1.40rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{rmse_2hr:.2f}",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

            else:
                with st.container(border=True):
                    st.markdown(
                        "### 🕒 2-Hour Ahead Forecast"
                    )

                    st.warning(
                        "No valid 2-hour-ahead forecast data is "
                        "available for overall performance."
                    )

    else:
        st.warning(
            "Not enough valid data to calculate "
            "overall forecast performance."
        )

# =====================================================
# MONTH-WISE OVERALL MAE — 2-HOUR AHEAD FORECAST
# =====================================================

monthly_2hr_performance, twohr_monthly_start, twohr_monthly_end = (
    calculate_monthly_2hr_mae(df)
)

if not monthly_2hr_performance.empty:

    show_section_heading(
        title="Month-Wise MAE of 2-Hour Ahead Forecast",
        start_date=twohr_monthly_start,
        end_date=twohr_monthly_end,
        icon="📅",
        heading_size="1.5rem"
    )

    with st.container(border=True):

        fig_monthly_2hr = go.Figure()

        fig_monthly_2hr.add_trace(go.Bar(
            x=monthly_2hr_performance["Month"],
            y=monthly_2hr_performance["Monthly_MAE"],
            name="2-Hour Ahead Forecast MAE",
            marker=dict(
                color=TWO_HOUR_COLOR,
                line=dict(
                    color="#1F7A1F",
                    width=1.2
                )
            ),
            text=[
                f"{value:.2f}"
                for value in monthly_2hr_performance["Monthly_MAE"]
            ],
            textposition="outside",
            cliponaxis=False,
            hovertemplate=(
                "<b>%{x}</b><br>"
                "MAE: %{y:.2f}"
                "<extra></extra>"
            )
        ))

        maximum_2hr_mae = (
            monthly_2hr_performance["Monthly_MAE"].max()
        )

        twohr_ymax = (
            maximum_2hr_mae * 1.18
            if pd.notna(maximum_2hr_mae) and maximum_2hr_mae > 0
            else 100
        )

        fig_monthly_2hr.update_layout(
            xaxis_title="Month",
            yaxis_title="MAE",
            height=500,
            bargap=0.25,
            showlegend=False,
            margin=dict(
                l=45,
                r=25,
                t=30,
                b=55
            )
        )

        fig_monthly_2hr.update_xaxes(
            type="category",
            categoryorder="array",
            categoryarray=[
                "Jan", "Feb", "Mar", "Apr",
                "May", "Jun", "Jul", "Aug",
                "Sep", "Oct", "Nov", "Dec"
            ],
            fixedrange=True
        )

        fig_monthly_2hr.update_yaxes(
            range=[0, twohr_ymax],
            rangemode="tozero",
            fixedrange=True
        )

        st.plotly_chart(
            fig_monthly_2hr,
            width="stretch",
            key="monthwise_2hour_forecast_mae",
            config={
                "displayModeBar": False,
                "staticPlot": True,
                "responsive": True
            }
        )

else:
    st.warning(
        "Not enough valid 2-hour-ahead forecast data is available "
        "to calculate month-wise MAE."
    )

# =====================================================
# TIME-SLOT-WISE MAPE — 2-HOUR AHEAD FORECAST
# Each bar represents the average MAPE at that time
# across all available days
# =====================================================

@st.cache_data
def calculate_timeslot_2hr_mape(input_df):

    timeslot_mape_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    timeslot_mape_df["hour"] = (
        timeslot_mape_df["valid_time_ist"].dt.hour
        + timeslot_mape_df["valid_time_ist"].dt.minute / 60
    )

    # Same evaluation conditions used in the dashboard
    timeslot_mape_df = timeslot_mape_df[
        (timeslot_mape_df["hour"] >= 6.5)
        & (timeslot_mape_df["hour"] <= 17.5)
        & (timeslot_mape_df["Actual_GHI"] > 50)
    ].copy()

    if timeslot_mape_df.empty:
        return pd.DataFrame(), None, None

    # Absolute percentage error for each prediction
    timeslot_mape_df["APE"] = (
        (
            timeslot_mape_df["Actual_GHI"]
            - timeslot_mape_df["Two_Hour_Ahead_Forecast"]
        ).abs()
        / timeslot_mape_df["Actual_GHI"]
    ) * 100

    # Display time in 24-hour format
    timeslot_mape_df["Time_Slot"] = (
        timeslot_mape_df["valid_time_ist"].dt.strftime("%H:%M")
    )

    # Numeric value used to sort times correctly
    timeslot_mape_df["Time_Order"] = (
        timeslot_mape_df["valid_time_ist"].dt.hour * 60
        + timeslot_mape_df["valid_time_ist"].dt.minute
    )

    timeslot_mape_performance = (
        timeslot_mape_df
        .groupby(
            ["Time_Order", "Time_Slot"],
            as_index=False
        )
        .agg(
            Time_Slot_MAPE=("APE", "mean"),
            Prediction_Count=("APE", "size")
        )
        .sort_values("Time_Order")
        .reset_index(drop=True)
    )

    start_date = (
        timeslot_mape_df["valid_time_ist"].dt.date.min()
    )

    end_date = (
        timeslot_mape_df["valid_time_ist"].dt.date.max()
    )

    return (
        timeslot_mape_performance,
        start_date,
        end_date
    )


# =====================================================
# CALCULATE TIME-SLOT-WISE MAPE
# =====================================================

(
    timeslot_2hr_mape_performance,
    timeslot_2hr_mape_start,
    timeslot_2hr_mape_end
) = calculate_timeslot_2hr_mape(df)

# =====================================================
# INDIVIDUAL MAPE DISTRIBUTION — 2-HOUR AHEAD FORECAST
# Each valid timestamp is counted separately
# =====================================================

@st.cache_data
def calculate_individual_2hr_mape_distribution(input_df):

    distribution_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    distribution_df["hour"] = (
        distribution_df["valid_time_ist"].dt.hour
        + distribution_df["valid_time_ist"].dt.minute / 60
    )

    # Same evaluation conditions used in the dashboard
    distribution_df = distribution_df[
        (distribution_df["hour"] >= 6.5)
        & (distribution_df["hour"] <= 17.5)
        & (distribution_df["Actual_GHI"] > 50)
    ].copy()

    if distribution_df.empty:
        return pd.DataFrame(), None, None, 0

    # Percentage error for every individual timestamp
    distribution_df["Individual_MAPE"] = (
        (
            distribution_df["Actual_GHI"]
            - distribution_df["Two_Hour_Ahead_Forecast"]
        ).abs()
        / distribution_df["Actual_GHI"]
    ) * 100

    start_date = (
        distribution_df["valid_time_ist"].dt.date.min()
    )

    end_date = (
        distribution_df["valid_time_ist"].dt.date.max()
    )

    # Classify every timestamp separately
    distribution_df["MAPE_Range"] = pd.cut(
        distribution_df["Individual_MAPE"],
        bins=[
            0,
            5,
            10,
            15,
            20,
            np.inf
        ],
        labels=[
            "0–5%",
            ">5–10%",
            ">10–15%",
            ">15–20%",
            ">20%"
        ],
        include_lowest=True,
        right=True
    )

    category_order = [
        "0–5%",
        ">5–10%",
        ">10–15%",
        ">15–20%",
        ">20%"
    ]

    distribution_counts = (
        distribution_df["MAPE_Range"]
        .value_counts()
        .reindex(category_order, fill_value=0)
        .rename_axis("MAPE Range")
        .reset_index(name="Number of Predictions")
    )

    total_predictions = len(distribution_df)

    return (
        distribution_counts,
        start_date,
        end_date,
        total_predictions
    )


# =====================================================
# CALCULATE INDIVIDUAL DISTRIBUTION
# =====================================================

(
    individual_mape_distribution_df,
    individual_distribution_start,
    individual_distribution_end,
    total_individual_predictions
) = calculate_individual_2hr_mape_distribution(df)


# =====================================================
# TIME-SLOT-WISE MAPE AND PERIOD-WISE MAPE DISTRIBUTION
# =====================================================

# Shared MAPE categories and colours
MAPE_CATEGORY_ORDER = [
    "0–5%",
    ">5–10%",
    ">10–15%",
    ">15–20%",
    ">20%"
]

MAPE_DISTRIBUTION_COLORS = [
    "#5E35B1",  # 0–5%
    "#8E67C7",  # >5–10%
    "#EC407A",  # >10–15%
    "#AB47BC",  # >15–20%
    "#78909C"   # >20%
]


# =====================================================
# PREPARE PERIOD-WISE INDIVIDUAL MAPE DISTRIBUTIONS
# =====================================================

@st.cache_data
def calculate_periodwise_2hr_mape_distribution(input_df):

    period_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    period_df["hour"] = (
        period_df["valid_time_ist"].dt.hour
        + period_df["valid_time_ist"].dt.minute / 60
    )

    # Same evaluation rules as the rest of the dashboard
    period_df = period_df[
        (period_df["hour"] >= 6.5)
        & (period_df["hour"] <= 17.5)
        & (period_df["Actual_GHI"] > 50)
    ].copy()

    if period_df.empty:
        return {}, None, None

    period_df["Individual_MAPE"] = (
        (
            period_df["Actual_GHI"]
            - period_df["Two_Hour_Ahead_Forecast"]
        ).abs()
        / period_df["Actual_GHI"]
    ) * 100

    period_df["MAPE_Range"] = pd.cut(
        period_df["Individual_MAPE"],
        bins=[
            0,
            5,
            10,
            15,
            20,
            np.inf
        ],
        labels=MAPE_CATEGORY_ORDER,
        include_lowest=True,
        right=True
    )

    # Period assignment based on forecast target timestamp
    period_df["Day_Period"] = np.select(
        [
            (
                (period_df["hour"] >= 6.5)
                & (period_df["hour"] <= 9.5)
            ),
            (
                (period_df["hour"] >= 10.5)
                & (period_df["hour"] <= 13.5)
            ),
            (
                (period_df["hour"] >= 14.5)
                & (period_df["hour"] <= 17.5)
            )
        ],
        [
            "Morning",
            "Noon",
            "Evening"
        ],
        default="Outside"
    )

    start_date = period_df["valid_time_ist"].dt.date.min()
    end_date = period_df["valid_time_ist"].dt.date.max()

    period_results = {}

    # Overall distribution
    overall_counts = (
        period_df["MAPE_Range"]
        .value_counts()
        .reindex(
            MAPE_CATEGORY_ORDER,
            fill_value=0
        )
        .rename_axis("MAPE Range")
        .reset_index(name="Number of Predictions")
    )

    period_results["Overall"] = {
        "data": overall_counts,
        "total": len(period_df),
        "time_range": "06:30–17:30"
    }

    # Morning, noon and evening distributions
    period_time_ranges = {
        "Morning": "06:30–09:30",
        "Noon": "10:30–13:30",
        "Evening": "14:30–17:30"
    }

    for period_name, period_time_range in period_time_ranges.items():

        selected_period_df = period_df[
            period_df["Day_Period"] == period_name
        ].copy()

        period_counts = (
            selected_period_df["MAPE_Range"]
            .value_counts()
            .reindex(
                MAPE_CATEGORY_ORDER,
                fill_value=0
            )
            .rename_axis("MAPE Range")
            .reset_index(name="Number of Predictions")
        )

        period_results[period_name] = {
            "data": period_counts,
            "total": len(selected_period_df),
            "time_range": period_time_range
        }

    return period_results, start_date, end_date


(
    periodwise_mape_results,
    periodwise_mape_start,
    periodwise_mape_end
) = calculate_periodwise_2hr_mape_distribution(df)


# =====================================================
# FUNCTION FOR PERIOD-WISE DONUT CHART
# This function must be above the pie-chart display code
# =====================================================

def create_mape_distribution_pie(
    distribution_df,
    total_predictions,
    period_title,
    time_range
):

    fig = go.Figure()

    fig.add_trace(
        go.Pie(
            labels=distribution_df["MAPE Range"],
            values=distribution_df["Number of Predictions"],

            hole=0.48,

            marker=dict(
                colors=MAPE_DISTRIBUTION_COLORS,
                line=dict(
                    color="white",
                    width=2
                )
            ),

            texttemplate=(
                "<b>%{label}</b><br>"
                "%{percent:.1%}"
            ),

            textposition="auto",

            insidetextfont=dict(
                size=10,
                color="white"
            ),

            hovertemplate=(
                "<b>%{label}</b><br>"
                "Predictions: %{value}<br>"
                "Share: %{percent:.2%}"
                "<extra></extra>"
            ),

            sort=False,
            direction="clockwise",
            pull=[0.025, 0, 0, 0, 0],
            automargin=True,
            showlegend=False
        )
    )

    fig.update_layout(
        title=dict(
            text=(
                f"<b>{period_title}</b><br>"
                f"<span style='font-size:12px;'>"
                f"{time_range}"
                f"</span>"
            ),
            x=0.5,
            xanchor="center",
            font=dict(size=17)
        ),

        height=410,
        showlegend=False,

        annotations=[
            dict(
                text=(
                    f"<b>{total_predictions}</b><br>"
                    "<span style='font-size:10px;'>"
                    "Predictions"
                    "</span>"
                ),
                x=0.5,
                y=0.5,
                showarrow=False,
                align="center",
                font=dict(size=18)
            )
        ],

        margin=dict(
            l=15,
            r=15,
            t=65,
            b=20
        ),

        uniformtext=dict(
            minsize=8,
            mode="hide"
        )
    )

    return fig
    
# =====================================================
# MAPE ANALYSIS DISPLAY
# ROW 1: TIME-SLOT-WISE MAPE + OVERALL DISTRIBUTION
# ROW 2: MORNING + NOON + EVENING DISTRIBUTIONS
# =====================================================

if (
    not timeslot_2hr_mape_performance.empty
    and periodwise_mape_results
):

    show_section_heading(
        title="MAPE Analysis of 2-Hour Ahead Forecast",
        start_date=periodwise_mape_start,
        end_date=periodwise_mape_end,
        icon="🎯",
        heading_size="1.5rem",
        top_margin="18px",
        bottom_margin="10px"
    )

    # =====================================================
    # ROW 1
    # LEFT: TIME-SLOT-WISE MAPE
    # RIGHT: OVERALL MAPE DISTRIBUTION
    # =====================================================

    timeslot_col, overall_col = st.columns(
        [1, 1],
        gap="large"
    )

    # ---------------- TIME-SLOT-WISE MAPE ----------------
    with timeslot_col:

        with st.container(border=True):

            st.markdown(
                """
                <div style="
                    font-size:1.30rem;
                    font-weight:700;
                    margin-top:2px;
                    margin-bottom:8px;
                ">
                    ⏱️ Time-Slot-Wise MAPE
                </div>
                """,
                unsafe_allow_html=True
            )

            fig_timeslot_2hr_mape = go.Figure()

            fig_timeslot_2hr_mape.add_trace(
                go.Bar(
                    x=timeslot_2hr_mape_performance[
                        "Time_Slot"
                    ],
                    y=timeslot_2hr_mape_performance[
                        "Time_Slot_MAPE"
                    ],

                    marker=dict(
                        color=TWO_HOUR_COLOR,
                        line=dict(
                            color="#1F7A1F",
                            width=1.2
                        )
                    ),

                    text=[
                        f"{value:.2f}%"
                        for value in
                        timeslot_2hr_mape_performance[
                            "Time_Slot_MAPE"
                        ]
                    ],

                    textposition="outside",
                    cliponaxis=False,

                    customdata=timeslot_2hr_mape_performance[
                        "Prediction_Count"
                    ],

                    hovertemplate=(
                        "<b>Time: %{x}</b><br>"
                        "Average MAPE: %{y:.2f}%<br>"
                        "Predictions: %{customdata}"
                        "<extra></extra>"
                    ),

                    showlegend=False
                )
            )

            maximum_timeslot_mape = (
                timeslot_2hr_mape_performance[
                    "Time_Slot_MAPE"
                ].max()
            )

            timeslot_mape_ymax = (
                maximum_timeslot_mape * 1.22
                if (
                    pd.notna(maximum_timeslot_mape)
                    and maximum_timeslot_mape > 0
                )
                else 10
            )

            ordered_time_slots = (
                timeslot_2hr_mape_performance[
                    "Time_Slot"
                ].tolist()
            )

            fig_timeslot_2hr_mape.update_layout(
                xaxis_title="Time",
                yaxis_title="MAPE (%)",
                height=440,
                bargap=0.25,
                showlegend=False,
                margin=dict(
                    l=55,
                    r=25,
                    t=35,
                    b=55
                )
            )

            fig_timeslot_2hr_mape.update_xaxes(
                type="category",
                categoryorder="array",
                categoryarray=ordered_time_slots,
                tickmode="array",
                tickvals=ordered_time_slots,
                ticktext=ordered_time_slots,
                tickangle=0,
                fixedrange=True
            )

            fig_timeslot_2hr_mape.update_yaxes(
                range=[0, timeslot_mape_ymax],
                rangemode="tozero",
                fixedrange=True
            )

            st.plotly_chart(
                fig_timeslot_2hr_mape,
                width="stretch",
                key="timeslot_2hr_mape_row1",
                config={
                    "displayModeBar": False,
                    "staticPlot": True,
                    "responsive": True
                }
            )

    # ---------------- OVERALL MAPE PIE ----------------
    with overall_col:

        with st.container(border=True):
            st.markdown(
                """
                <div style="
                    font-size:1.30rem;
                    font-weight:700;
                    margin-top:2px;
                    margin-bottom:8px;
                ">
                    🎯 Overall MAPE Distribution
                </div>
                """,
                unsafe_allow_html=True
            )

            overall_information = (
                periodwise_mape_results["Overall"]
            )

            if overall_information["total"] > 0:

                overall_pie_figure = (
                    create_mape_distribution_pie(
                        distribution_df=overall_information[
                            "data"
                        ],
                        total_predictions=overall_information[
                            "total"
                        ],
                        period_title="",
                        time_range=overall_information[
                            "time_range"
                        ]
                    )
                )

                overall_pie_figure.update_layout(
                    height=440,
                    margin=dict(
                        l=10,
                        r=10,
                        t=70,
                        b=15
                    )
                )

                st.plotly_chart(
                    overall_pie_figure,
                    width="stretch",
                    key="overall_2hr_mape_row1",
                    config={
                        "displayModeBar": False,
                        "staticPlot": True,
                        "responsive": True
                    }
                )

            else:
                st.markdown("### Overall")

                st.info(
                    "No valid predictions are available "
                    "for the overall distribution."
                )

    # =====================================================
    # ROW 2 HEADING
    # =====================================================

    st.markdown(
        """
        <div style="
            font-size:1.30rem;
            font-weight:700;
            margin-top:20px;
            margin-bottom:10px;
        ">
            🕒 Period-Wise MAPE Distribution
        </div>
        """,
        unsafe_allow_html=True
    )

    # =====================================================
    # ROW 2: MORNING, NOON AND EVENING
    # =====================================================

    morning_col, noon_col, evening_col = st.columns(
        3,
        gap="large"
    )

    period_chart_settings = [
        (
            morning_col,
            "Morning",
            "morning_2hr_mape_row2"
        ),
        (
            noon_col,
            "Noon",
            "noon_2hr_mape_row2"
        ),
        (
            evening_col,
            "Evening",
            "evening_2hr_mape_row2"
        )
    ]

    for column, period_name, chart_key in period_chart_settings:

        period_information = periodwise_mape_results[
            period_name
        ]

        with column:

            with st.container(border=True):

                if period_information["total"] > 0:

                    period_pie_figure = (
                        create_mape_distribution_pie(
                            distribution_df=period_information[
                                "data"
                            ],
                            total_predictions=period_information[
                                "total"
                            ],
                            period_title=period_name,
                            time_range=period_information[
                                "time_range"
                            ]
                        )
                    )

                    period_pie_figure.update_layout(
                        height=420,
                        margin=dict(
                            l=15,
                            r=15,
                            t=70,
                            b=20
                        )
                    )

                    st.plotly_chart(
                        period_pie_figure,
                        width="stretch",
                        key=chart_key,
                        config={
                            "displayModeBar": False,
                            "staticPlot": True,
                            "responsive": True
                        }
                    )

                else:
                    st.markdown(
                        f"### {period_name}"
                    )

                    st.info(
                        "No valid predictions are available "
                        "for this period."
                    )

else:

    if timeslot_2hr_mape_performance.empty:
        st.warning(
            "Not enough valid 2-hour-ahead forecast data "
            "is available to calculate time-slot-wise MAPE."
        )

    if not periodwise_mape_results:
        st.warning(
            "Not enough valid 2-hour-ahead forecast data "
            "is available to calculate MAPE distributions."
        )

# =====================================================
# POSITIVE AND NEGATIVE BIAS DISTRIBUTION
# 2-HOUR AHEAD FORECAST
# =====================================================

@st.cache_data
def calculate_2hr_bias_distributions(input_df):

    bias_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    bias_df["hour"] = (
        bias_df["valid_time_ist"].dt.hour
        + bias_df["valid_time_ist"].dt.minute / 60
    )

    # Same evaluation rules used elsewhere
    bias_df = bias_df[
        (bias_df["hour"] >= 6.5)
        & (bias_df["hour"] <= 17.5)
        & (bias_df["Actual_GHI"] > 50)
    ].copy()

    if bias_df.empty:
        return (
            pd.DataFrame(),
            pd.DataFrame(),
            None,
            None,
            0,
            0
        )

    # Signed percentage bias
    bias_df["Percentage_Bias"] = (
        (
            bias_df["Two_Hour_Ahead_Forecast"]
            - bias_df["Actual_GHI"]
        )
        / bias_df["Actual_GHI"]
    ) * 100

    start_date = (
        bias_df["valid_time_ist"]
        .dt.date
        .min()
    )

    end_date = (
        bias_df["valid_time_ist"]
        .dt.date
        .max()
    )

    # Positive bias = forecast greater than actual
    positive_bias_df = bias_df[
        bias_df["Percentage_Bias"] > 0
    ].copy()

    # Negative bias = forecast less than actual
    negative_bias_df = bias_df[
        bias_df["Percentage_Bias"] < 0
    ].copy()

    # Use absolute magnitude for range classification
    positive_bias_df["Bias_Magnitude"] = (
        positive_bias_df["Percentage_Bias"].abs()
    )

    negative_bias_df["Bias_Magnitude"] = (
        negative_bias_df["Percentage_Bias"].abs()
    )

    category_order = [
        "0–5%",
        ">5–10%",
        ">10–15%",
        ">15–20%",
        ">20%"
    ]

    bins = [
        0,
        5,
        10,
        15,
        20,
        np.inf
    ]

    # Positive-bias categories
    positive_bias_df["Bias_Range"] = pd.cut(
        positive_bias_df["Bias_Magnitude"],
        bins=bins,
        labels=category_order,
        include_lowest=True,
        right=True
    )

    positive_distribution = (
        positive_bias_df["Bias_Range"]
        .value_counts()
        .reindex(
            category_order,
            fill_value=0
        )
        .rename_axis("Bias Range")
        .reset_index(name="Number of Predictions")
    )

    # Negative-bias categories
    negative_bias_df["Bias_Range"] = pd.cut(
        negative_bias_df["Bias_Magnitude"],
        bins=bins,
        labels=category_order,
        include_lowest=True,
        right=True
    )

    negative_distribution = (
        negative_bias_df["Bias_Range"]
        .value_counts()
        .reindex(
            category_order,
            fill_value=0
        )
        .rename_axis("Bias Range")
        .reset_index(name="Number of Predictions")
    )

    return (
        positive_distribution,
        negative_distribution,
        start_date,
        end_date,
        len(positive_bias_df),
        len(negative_bias_df)
    )


# =====================================================
# CALCULATE BIAS DISTRIBUTIONS
# =====================================================

(
    positive_bias_distribution,
    negative_bias_distribution,
    bias_start_date,
    bias_end_date,
    total_positive_bias_predictions,
    total_negative_bias_predictions
) = calculate_2hr_bias_distributions(df)


# =====================================================
# DONUT CHART FUNCTION FOR BIAS DISTRIBUTION
# =====================================================

def create_bias_distribution_pie(
    distribution_df,
    total_predictions,
    chart_title,
    center_label
):

    fig = go.Figure()

    fig.add_trace(
        go.Pie(
            labels=distribution_df["Bias Range"],
            values=distribution_df["Number of Predictions"],

            hole=0.48,

            marker=dict(
                colors=MAPE_DISTRIBUTION_COLORS,
                line=dict(
                    color="white",
                    width=2
                )
            ),

            texttemplate=(
                "<b>%{label}</b><br>"
                "%{percent:.1%}"
            ),

            textposition="auto",

            insidetextfont=dict(
                size=11,
                color="white"
            ),

            hovertemplate=(
                "<b>%{label}</b><br>"
                "Predictions: %{value}<br>"
                "Share: %{percent:.2%}"
                "<extra></extra>"
            ),

            sort=False,
            direction="clockwise",
            pull=[0.025, 0, 0, 0, 0],
            automargin=True,
            showlegend=False
        )
    )

    fig.update_layout(
        title=dict(
            text=f"<b>{chart_title}</b>",
            x=0.5,
            xanchor="center",
            font=dict(size=18)
        ),

        height=440,
        showlegend=False,

        annotations=[
            dict(
                text=(
                    f"<b>{total_predictions}</b><br>"
                    f"<span style='font-size:11px;'>"
                    f"{center_label}"
                    f"</span>"
                ),
                x=0.5,
                y=0.5,
                showarrow=False,
                align="center",
                font=dict(size=20)
            )
        ],

        margin=dict(
            l=20,
            r=20,
            t=70,
            b=20
        ),

        uniformtext=dict(
            minsize=8,
            mode="hide"
        )
    )

    return fig


# =====================================================
# DISPLAY POSITIVE AND NEGATIVE BIAS PIES
# BOTH IN ONE ROW INSIDE ONE OUTER BOX
# =====================================================

if (
    not positive_bias_distribution.empty
    or not negative_bias_distribution.empty
):

    show_section_heading(
        title="Bias Distribution of 2-Hour Ahead Forecast",
        start_date=bias_start_date,
        end_date=bias_end_date,
        icon="⚖️",
        heading_size="1.5rem",
        top_margin="20px",
        bottom_margin="10px"
    )
    
    st.markdown(
        """
        <div style="
            font-size:0.95rem;
            color:inherit;
            margin-top:-4px;
            margin-bottom:12px;
        ">
            <b>Positive Bias:</b> Forecast GHI &gt; Actual GHI (Overprediction)
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <b>Negative Bias:</b> Forecast GHI &lt; Actual GHI (Underprediction)
        </div>
        """,
        unsafe_allow_html=True
    )
    
    with st.container(border=True):
    
        positive_col, negative_col = st.columns(
            2,
            gap="large"
        )

        # =====================================================
        # POSITIVE BIAS
        # =====================================================

        with positive_col:

            if total_positive_bias_predictions > 0:

                fig_positive_bias = (
                    create_bias_distribution_pie(
                        distribution_df=positive_bias_distribution,
                        total_predictions=total_positive_bias_predictions,
                        chart_title="Positive Bias Distribution",
                        center_label="Overpredictions"
                    )
                )

                st.plotly_chart(
                    fig_positive_bias,
                    width="stretch",
                    key="positive_2hr_bias_distribution",
                    config={
                        "displayModeBar": False,
                        "staticPlot": True,
                        "responsive": True
                    }
                )

            else:
                st.markdown(
                    "### 📈 Positive Bias Distribution"
                )

                st.info(
                    "No positive-bias predictions are available."
                )

        # =====================================================
        # NEGATIVE BIAS
        # =====================================================

        with negative_col:

            if total_negative_bias_predictions > 0:

                fig_negative_bias = (
                    create_bias_distribution_pie(
                        distribution_df=negative_bias_distribution,
                        total_predictions=total_negative_bias_predictions,
                        chart_title="Negative Bias Distribution",
                        center_label="Underpredictions"
                    )
                )

                st.plotly_chart(
                    fig_negative_bias,
                    width="stretch",
                    key="negative_2hr_bias_distribution",
                    config={
                        "displayModeBar": False,
                        "staticPlot": True,
                        "responsive": True
                    }
                )

            else:
                st.markdown(
                    "### 📉 Negative Bias Distribution"
                )

                st.info(
                    "No negative-bias predictions are available."
                )

else:
    st.warning(
        "Not enough valid 2-hour-ahead forecast data is available "
        "to calculate positive and negative bias distributions."
    )
